### ISSUE TITLE
In order to present more readable typography to users, control leading and kerning of instances of Karla

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#155]
Karla had been working BEAUTIFULLY on the site so far, especially in tables and fields with a lot of numerals, but we could help it out if we added some specific controls to a few instances:

#### 1. set `line-height: 1.4rem;` When used as a table header 
so that this (current)

<img width="1006" alt="screen shot 2015-10-21 at 6 56 36 pm" src="https://cloud.githubusercontent.com/assets/11636908/10652749/18167bf2-7827-11e5-92da-1998c541abe5.png">

looks more like this (ideal)

<img width="1004" alt="screen shot 2015-10-21 at 6 56 11 pm" src="https://cloud.githubusercontent.com/assets/11636908/10652750/181679ea-7827-11e5-9f5c-908d37937871.png">

#### 2. set `letter-spacing: -.03rem;` When used as body copy or list items 
so that this (current)

<img width="1250" alt="screen shot 2015-10-21 at 7 12 38 pm" src="https://cloud.githubusercontent.com/assets/11636908/10652878/2073c006-7828-11e5-9f45-766f1b25a61d.png">

looks more like this (ideal)

<img width="1252" alt="screen shot 2015-10-21 at 7 14 35 pm" src="https://cloud.githubusercontent.com/assets/11636908/10652866/0979ea92-7828-11e5-9cee-68fb85a5bd89.png">

and this (current)

<img width="1247" alt="screen shot 2015-10-21 at 7 13 52 pm" src="https://cloud.githubusercontent.com/assets/11636908/10652891/30ad5c0c-7828-11e5-8f40-2396a574a445.png">

looks more like this (ideal)

<img width="1251" alt="screen shot 2015-10-21 at 7 13 42 pm" src="https://cloud.githubusercontent.com/assets/11636908/10652896/36f441a2-7828-11e5-946c-159cde32d836.png">

These screen shots really aren't doing the change justice in the last instance, but when you toggle it you do see the difference. I'd be wiling to concede on the second item if it's *really really* complicated to implement.

**Comment by noahmanger** [comment]
Story card: https://18f.storiesonboard.com/m/fec/!card/dSDD9jsDpx8iGTnTwnAhdQ

**Comment by noahmanger** [comment]
Ok, I addressed this in the big styleguide PR. 

The first one is easy. The second one is a little trickier. Because we set the font for all these elements separately (i.e. there's no single class for them), you can't say "all of these instances, set the letter-spacing". I went through and found places where I thought you would want it, though, and set it manually.

It raises a small concern about future maintainability, but I'm not too worried about it.

Would be good for you to checkout that PR now and see if things are showing up like you want.
