### ISSUE TITLE
To help users log feedback, make the feedback widget not so awkwardly tall

### ISSUE THREAD

**Issue by jmcarp** [18F/fec-style#161]
I think I've asked about this before, but I think this looks silly:

<img width="705" alt="screen shot 2015-10-24 at 4 24 54 pm" src="https://cloud.githubusercontent.com/assets/1633460/10712579/1af4bcfc-7a6c-11e5-87a2-b97d9437b7c9.png">

cc @noahmanger @jenniferthibault

**Comment by noahmanger** [comment]
Card: https://18f.storiesonboard.com/m/fec/!card/A3Fbqb1-4zJW9jnUEFZhfg

**Comment by noahmanger** [comment]
So the reason that this is the way it is is because we set the height to the vertical size of the viewport. I've tried other ways, but the long story short is that not doing it this way means that if we have a short viewport, you can't control for it to not extend _above_ it.

And adjusting the height with JS or something so that it shrinks when the message replaces the form seems like it may be a jarring transition.

I think the only good option is to redesignt his from a panel that slides up from the bottom to more of a typical modal. Or we can decide that the weird height thing is ok.

@jenniferthibault ?

**Comment by jenniferthibault** [comment]
What's "more of a typical modal" like @noahmanger ?

In this scenario, as the tool's built now, I'd prefer for the tool to stay the same size, (placing beginning reading point at the same spot) rather than resizing and getting very short here, which would jump the readers' eye all around the page and be disorienting.

**Comment by noahmanger** [comment]
I'm thinking more along the lines of the download modal, where it pops up and takes control of the entire screen. We had previously voted this idea down because it makes the rest of the page unusable while open though.

**Comment by jenniferthibault** [comment]
Oh oh oh. Gotcha. Right.

I think being able to see the page you're giving feedback on clearly is a good feature. I'd prefer to sacrifice awkward height for page visibility.

BUT!

To counter my own point on consistent text positioning for eye movement, it may not be such a jarring transition if the panel gently slides down to fit the success or error message after the issue was received. (JS?) I'd be up for seeing how this looks (I say as the person who doesn't know how to implement it).

**Comment by jenniferthibault** [comment]
This is no longer an issue, right @noahmanger ?
