### ISSUE TITLE
Extract code for filter-tags from 18f/fec-style#styling-calendars

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#228]
In order to release the filter-tags on the data web app, we should extract the necessary files from https://github.com/18F/fec-style/pull/213/.

**Comment by jmcarp** [comment]
Taking another look at the work in this branch, I'm thinking it's not worth the time to separate code related to filters and the calendar. There are a lot of commits to sort through--and as it turns out, the calendar-related changes are all css changes that shouldn't have any effect until the calendar feature is merged into fec-cms.

**Comment by noahmanger** [comment]
Sounds good. Closing.
