### ISSUE TITLE
Update visual design of styleguide

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#283]

**Comment by jenniferthibault** [comment]
Goal: Clearly distinguish what elements are the style guide framework from the elements that are in the betaFEC style. 

To that end, I've adopted the US Web design standards' basic style for the framework, while mixing in gentle elements (like color palette) and a more official branded header space to make it feel like a system that is designed FOR the betaFEC system, but is not part of the recommendations.

Again, trying to keep changes minimal for now so that we can build on this once we decide on a strategy #280 


![web-style-guide-1](https://cloud.githubusercontent.com/assets/11636908/14571115/8d7d7a70-0315-11e6-8a63-558faac5a3c1.png)

![web-style-guide-2](https://cloud.githubusercontent.com/assets/11636908/14571116/8d7f85d6-0315-11e6-979b-b41e72795b71.png)

**Comment by jenniferthibault** [comment]
Ifffff it's helpful, here are screenshots of the basic grid alignments I was using, based on a 960 grid:

![screen shot 2016-04-15 at 3 03 49 pm](https://cloud.githubusercontent.com/assets/11636908/14574828/dbb414d6-032b-11e6-8f7b-044a87ddb0cc.png)
![screen shot 2016-04-15 at 3 04 10 pm](https://cloud.githubusercontent.com/assets/11636908/14574829/dbb5b1b0-032b-11e6-9a1b-a9ecf6d8194d.png)

**Comment by jenniferthibault** [comment]
Closed by #317
