### ISSUE TITLE
Implement new checkbox designs

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#320]

**Comment by noahmanger** [comment]
Ok! How's this looking, @jenniferthibault ? When on dark backgrounds I just made the border white and the check mark the base color. And although we don't use radio buttons much, they were styled together already, so I applied the same styles here.

Last, I wasn't sure if you wanted to keep the outline on focus, but I left it. Let me know if you want to change it. Here's how it looks in the style guide and on the site:

![image](https://cloud.githubusercontent.com/assets/1696495/14872116/fc033c8c-0c9d-11e6-9bd8-90b6f05042a4.png)

![image](https://cloud.githubusercontent.com/assets/1696495/14872431/17a075ec-0ca1-11e6-9464-d02a94b218fe.png)

![image](https://cloud.githubusercontent.com/assets/1696495/14872440/263e658c-0ca1-11e6-8407-fc0021935ff9.png)

**Comment by jenniferthibault** [comment]
For context: I know that most of this is due to my mockups not being well-annotated. I'll do better!

One goal of this is to make the difference between checked and unchecked items more obvious at a quick glance. To that end, the background color of unchecked items should have a fill of a solid color. Checked items should have no background fill.

On focus states, the state should apply to the whole hit area, not just the checkbox. I was thinking we could use the blue outline we use for the rest of the site. This (and the fill application) seen here:

![screen shot 2016-04-28 at 3 57 02 pm](https://cloud.githubusercontent.com/assets/11636908/14899476/2e11d208-0d5a-11e6-99c1-935a8977df46.png)


On colored backgrounds, I'm hoping to keep the palette of greys in the hit aread (like buttons) if we can:

![screen shot 2016-04-28 at 4 08 25 pm](https://cloud.githubusercontent.com/assets/11636908/14899759/8a8871b2-0d5b-11e6-9751-9af000e1cb71.png)


We haven't yet encountered a scenario where we've needed to use form elements on a solid background on the site, so for now those are still hypothetical. 

And yep, these should all be identical on the radio buttons :)
