### ISSUE TITLE
Prepare simple icons for SVG workflow improvements 

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#328]
To help improve the SVG workflow in #282 

- get all simple icons into one Sketch file
- make height uniform across all icons
- make sure all paths are uniform & subtracted
- export icons as svgs into existing branch

cc @noahmanger

**Comment by jenniferthibault** [comment]
@noahmanger do you want to take a look before I export? 

I tried to make them mostly uniform size and uniform stroke weight, so we should keep an eye on where these appear in context and may need to make some sizing adjustments through CSS.

[betaFEC_icons.sketch.zip](https://github.com/18F/fec-style/files/239603/betaFEC_icons.sketch.zip)

**Comment by noahmanger** [comment]
Nice! Just tried it out with some and seems to be working well. 

![image](https://cloud.githubusercontent.com/assets/1696495/14873277/870d95a6-0ca9-11e6-890a-9809103e0735.png)

Only weird thing is the table and calendar icons are just showing up as a solid block. Might be because they of the way the subtraction is working. But we can trouble shoot those on a case-by-case basis. 

Go ahead and get this to whichever state feels good and then I'll take it from there!

**Comment by jenniferthibault** [comment]
Icons have been exported, now just need to make them show up in context. Closing this in favor of those adjustments happening in https://github.com/18F/fec-style/pull/334
