### ISSUE TITLE
Design interaction pattern for subscribing to email list

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#459]
Users need to be able to sign up for email notifications from the FEC from time to time.

We are seeing this pattern first on the Record pages, which are circulated by email:
http://www.fec.gov/pages/fecrecord/2016/july/15monthsummary2016cycle.shtml

But it will probably be useful as we get deeper into outreach, media, events etc.

Probably a cousin to this interaction is the "Subscribe" functionality seen on the calendar https://beta.fec.gov/calendar/
<img width="456" alt="screen shot 2016-08-10 at 2 21 55 pm" src="https://cloud.githubusercontent.com/assets/11636908/17565541/d8aef586-5f05-11e6-80bc-f54161b20742.png">

cc @onezerojeremy who mentioned wanting to think holistically about subscribe interactions

**Comment by jenniferthibault** [comment]
"Subscribe" holistically includes looking at:
- RSS
- Calendar
- Email

**Comment by emileighoutlaw** [comment]
I've been looking at things _like_ this for other content components, and I am extremely thumbs up to the "subscribe" microcopy.  (just so you know you have my enthusiastic support 😁 )

**Comment by nickykrause** [comment]
Some notes I took regarding the existing subscribe interactions:

[Calendar](https://beta.fec.gov/calendar/)
- Re: Calendar interface on mobile. The text for the “Subscribe” button options are cut off in both Chrome (tested on Android) and Safari (tested on iOS).
- Re: Calendar interaction on mobile. Android interaction takes user to browser instead of launching native calendar (forces user to log into browser even if already logged in natively). The iOS interaction is better: it launches the native app. Can we make the Android interaction smoother, or is there something about the Google Calendar native app for Android that would prevent us from doing that?

[Records pages](http://www.fec.gov/pages/fecrecord/2016/july/15monthsummary2016cycle.shtml)
- Looks like this integrates with a service called GovDelivery. The subscribe interactions we design will need to use that service too, yes?
- The subscribe link on the records pages opens a sort of “subscription wizard” in a new window
- There is also a subscribe link on the contact us page. This link takes the user to a subscribe page, from which the “subscription wizard” opens in the same window.
- When subscribing to email updates, the user has the option to choose from a long list of topics / categories. Our subscribe interaction may need the same


[RSS Feeds](http://www.fec.gov/rss/RSSFeeds.shtml#search=rss)
- Do we have data about the use of these feeds or access to the RSS Feeds page? I can’t find anything in Google Analytics. Maybe that means there is no data (literally no visitors). For reference, I’m looking in Behavior > Site Content > All Pages, with an advanced filter set to search page for titles containing “RSS” or “RSS Feeds. Also looking at a date range of the last year. Maybe there is a flaw in my search?
- How does a person even access the RSS page on fec.gov? I don’t see an obvious navigation link to it, but I was able to find it by searching with the search bar. Path is Home / RSS Feeds.

Other thoughts on the future of subscribe features:
- Calendar: Other than the issues noted above regarding the current Calendar interaction, I don't have an issue with it. Do others have concerns about it? We could test its usability if we are worried.
- RSS: Does anyone use the RSS feeds? Is this something we need to continue to offer? Can we find out more about how popular/useful this feature is, and/or how strongly the partners feel about keeping it? (Perhaps it has some niche use that we don't know about?)
- Email: I've looked at the existing process and need to reflect on the experience of signing up & updating preferences.
- Holistic: The current site offers a "subscribe page" that explains how to subscribe for email, but which contains no information about other kinds of subscriptions (calendar, RSS). A few thoughts: Do we need a similar page? If so, what should go on it? Would we make that page a more holistic snapshot of the various ways to "subscribe" to receive FEC communications?

**Comment by LindsayYoung** [comment]
Some people do use RSS feeds, but the developers that use them could switch to the API for most data things. Since google discontinued its RSS reader, I think a lot fewer people use RSS feeds. I like the idea of seeing how popular they are.

If there is a specific need for them, we should make feeds.  

For the content, they should not be hard to make:
https://chrxr.com/adding-rss-feed-wagtail-site/

They aren't hard for the data per se, I think we could use the same base views and queries and then add martial them differently. I am not sure how labor intensive it would be to figure out.

**Comment by jenniferthibault** [comment]
This is slightly outdated, so closing in favor of https://github.com/18F/fec-cms/issues/1044
