### ISSUE TITLE
Create template page for historical archive lists of documents

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-style#540]
For example:
- complete list of commission meetings
  - agenda from that meeting
  - podcast from that meeting
  - transcript from that meeting
- complete list of sunshine act notices
- complete list of public hearings
  - associated documents
- and others that we'll learn more about along the way

**Comment by jenniferthibault** [comment]
Carrying over from #555:

For looking at index pages there are a few possible flows:

- Collections/groups of documents that have similar utility to users
  - document type/title
  - sometimes (but not always) an explanation of what the document title means
  - number of documents of that type that exist in each index

- Lists / indexes of the documents all in one place
  - ability to sort by date/quickly see item date
  - sometimes (but not always) ability to filter by category within item type
  - when item is HTML, ability to view snippet text and link to document canonical page
  - when item does not have HTML copy, ability to easily and quickly access native doc and associated collateral (agendas; transcripts; recordings; sometimes PDFs, sometimes XLS)

- Canonical item page
  - HTML body copy
  - associated collateral (agendas; transcripts; recordings; sometimes PDFs, sometimes XLS)
 

We pretty much have _templates_ that fit each scenario 🎉 , but it will be helpful for me to mock up a few specifics about each, especially in cases where we don't have HTML pages, or where we want to attach associated collateral.

cc @emileighoutlaw

**Comment by noahmanger** [comment]
Just running through things before the demo on Monday. @jenniferthibault do you have anything done that you'd want me to show partners in our end-of-sprint demo?

**Comment by jenniferthibault** [comment]
I finished work on this over the weekend, but don't think it's really demo-able. It's a long series of patterns & flows.  I'm going to update this issue this morning, and if it's before your demo, and you think it makes sense, go for it.

**Comment by jenniferthibault** [comment]
## General pattern flows:
1 - [A] Groups of related documents »  [B] Browsing within document type  »  [C] Canonical item page
2 - [B] Browsing within document type  »  [C] Canonical item page

### [A] Groups of related documents
This is the first new pattern in the card family. It's flexible enough to hold a title, brief explainer copy, and document count. It works best in 3-across grids, but should also work in 2-across grids.

If desired, we could implement search across this pattern.


![screen shot 2016-11-07 at 10 46 02 am](https://cloud.githubusercontent.com/assets/11636908/20064072/688c0768-a4d7-11e6-83af-8791ab3e4999.png)



### [B] Browsing within document type: feed
This is an existing module (first seen in the Latest Updates feed) that will need case-by-case tweaks to accommodate: 
- Filtering parameters
- Item/document completeness. Sometimes items have HTML copy, other times they are just PDFs that will be ported over into an archive. 

![screen shot 2016-11-07 at 10 46 25 am](https://cloud.githubusercontent.com/assets/11636908/20064093/79f925d0-a4d7-11e6-8d45-afc75b61d710.png)



### [C] Canonical item page
Each item in the feed should link to a canonical page for the item, regardless of level of completeness. Each canonical item should have a shareable unique URL.
We have several existing templates for these pages, including the Weekly digest template, a Registration and Reporting item template, and the in-progress Agenda template.

![screen shot 2016-11-07 at 10 47 55 am](https://cloud.githubusercontent.com/assets/11636908/20064158/bbe02764-a4d7-11e6-8bc7-2908887c7683.png)
![screen shot 2016-11-07 at 10 48 17 am](https://cloud.githubusercontent.com/assets/11636908/20064157/bbe01a26-a4d7-11e6-9b0d-01b01f1ff867.png)




## Next steps

@noahmanger / @emileighoutlaw I'd love your help here, not quite sure what comes next.

We could pick a set of items to port over into the new template flows. I think the meeting agenda archive fits neatly into Flow 2 above, and could be a possibility. That means we'd need to finalize the Wagtail agenda template, decide on filtering parameters for open meeting archives, design icons for transcripts and audio, scrape content, etc.

Or we could focus on building out the new card pattern for Flow 1 that would make this a complete set. As of yet I'm not sure if there's agreement on which groups of related documents might go together first, so it might be a while before we use what we'd build.

Or another way forward I haven't mentioned?

**Comment by noahmanger** [comment]
Sorry it's taken me so long to get to this. I really love these. The only question I have is if a resource doesn't have any actual HTML (e.g. it's just a PDF or MP3) do we need to give it its own page? Doing so makes for an unnecessary step, and leads to pages that are empty except for a link. But on the other hand, it might make it easier for people to share. 

I don't have strong feelings — and could be persuaded by one being easier to develop than the other — but wanted to throw that out there.

**Comment by jenniferthibault** [comment]
Even though it will make many scant pages, since these pages are serving archival & research needs, I think having a unique URL for each would be helpful. Otherwise it will be hard to find these documents, transcripts, and details again without finding their position in a feed.

Do you agree, @emileighoutlaw ?

**Comment by emileighoutlaw** [comment]
Oh a great question! For PDF documents — researchers could theoretically open them in their browsers and save those PDF URLs for future reference, right? Would that serve the same need?

**Comment by emileighoutlaw** [comment]
I spent some time looking at these templates and the content that's left to port over from FEC.gov— At a first look, I think our templates (Registration and reporting, Weekly Digest, and the in-progress Agenda) should fit all the needs for our canonical pages. 

A thought— we _don't_ have a `Read next` feature in our Registration and reporting template (We've been using the `Related topics` to guide people in that section of the website), but we do in all the others. This is probably outside the scope of this issue, but I'm wondering if either of y'all think we should consider adding that to our Registration and reporting template for consistency. 

Next steps— I'd be eager to dive into something small but useful. Like FOIA reports? But I think that's a Flow 1 item, because it's housed inside the "About FEC" section.

**Comment by noahmanger** [comment]
@emileighoutlaw yeah, you're right, their PDF URL would always work as a bookmark / permalink.

Re: "read next" -- we decided not to do this for registration and reporting because so many of the pages are shared by different checklists with different flows.

Re: next steps, do you have a set of documents that will fall into these flows?

**Comment by emileighoutlaw** [comment]
Ah, that's right about the "next" feature. Thanks for jogging my memory, Noah.

Documents for these flows:

Organizational information
IG reports
Commissioner pages
FOIA

**Flow 2 (browsing within `Latest updates`)**
- FEC record articles
- Tips for Treasurers
- Sunshine notices (notices that a meeting is going to happen and generally what will be discussed at that meeting)
- Meeting agendas (published after Sunshine notices and including more detail)

**Comment by emileighoutlaw** [comment]
After our chat, I now fear my comment (above) jumped a few steps.

I was imagining that — because we are planning to include many different groups of documents in the `About FEC` section — the design of the `About FEC` landing page would include cards (and then feeds) for at least a portion of those document types. However, holding my horses, I think a better answer is:


Every document type that we have said we'll include in `Latest updates` should be part of the `Latest updates` feed. Those document types are:
- FEC record articles
- Tips for Treasurers
- Sunshine notices (notices that a meeting is going to happen and generally what will be discussed at that meeting)
- Meeting agendas (published after Sunshine notices and including more detail 


The things that will be included in the `About FEC` section (however that gets designed) will be:
- Department and office pages _(~30 HTML pages)_
- Legislative recommendations, history, and reports _(~50 mix of PDF/HTML pages)_
- Strategic plans _(~8 mix of PDF/HTML pages)_
- Budget plans and reports _(~100 mix of PDF/HTML pages)_
- FEC policies and directives _(~50 mix of PDF/HTML pages)_
- Annual reports; anniversary reports _(~35 PDF pages)_
- Procurement reports _(~10 PDF pages)_
- IG reports _(~150 mix of PDF/HTML pages)_
- Commissioner pages _(~690 mix of PDF/HTML pages)_
- FOIA  _(~30 mix of PDF/XML pages)_

But I'll wait to talk strategy and design of the `About FEC` section with @jenniferthibault.

**Comment by jenniferthibault** [comment]
@emileighoutlaw do you want to close this issue in favor of advancing to https://github.com/18F/fec-cms/issues/626 , or leave it open for anything remaining here?

**Comment by noahmanger** [comment]
I was just about to close this! #626 is a next step, and I'll be making issues for porting over the rest of the latest updates stuff.
