### ISSUE TITLE
Scope template design work for content migration

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#555]
So that we can plan and begin to tackle the work of designing new templates for content that needs to be ported over, identify shared templates and patterns based on the content inventory spreadsheet.

---

**Completion criteria:**
- [ ] Identify pages that need new templates from what we have now
- [ ] Identify new components we need
- [ ] Identify what will be editable in the CMS and what will be hard coded

**Comment by jenniferthibault** [comment]
Pre-emptively tagging myself in on this, but it's unclear so far if it's a totally shared task between content & design, or if it can be led by one or the other. I suspect we'll learn as soon as we start :) Going to the calendar to set some time for @emileighoutlaw & I to dig into the spreadsheet together now.

**Comment by jenniferthibault** [comment]
@emileighoutlaw and I chatted this morning, and the short version is that I don't think it will ever be possible to look at the entire content inventory and make a comprehensive list of what new templates we need, because we don't know where things are going to live/how you're going to get to them until shortly before they become priorities. #agile 

BUT, what we do know for now, is there is a clear need to plan for how one content type lives and is navigated between: indexes or lists of documents, which we've already captured an example of in https://github.com/18F/fec-style/issues/540 . I'm going to move that issue into sprint 25, flesh out other completion criteria, and make that the working place for this task this sprint.

**Comment by noahmanger** [comment]
Sounds excellent. In that case, going to close this issue.
