### ISSUE TITLE
Documentation: Describe reasons for not adopting USWDS

### ISSUE THREAD

**Issue by asarazor** [18F/fec-style#612]
For contributors and other government designers it would be really helpful to know why fec-style is not based on the [US Web Design Standards](https://standards.usa.gov) (beyond a few references). No doubt there were business reasons for this decision, but from the outside it's a little puzzling given that both projects have a lot of 18F involvement. Perhaps a little section on the Wiki or on README.md.

Note: Obviously this is really just a question I have, but I tried to re-frame it in a way that could also benefit the wider govt. digital services community.

**Comment by jenniferthibault** [comment]
Hi Rob, thanks for the question! I joined the team in early 2015 as part of a shift of designers  charting what a new fec.gov might be like, and we've thought about this a lot. 

Short answer: Our timeline just didn't work with the US Web Design Standards' deliverables timeline. 

Longer answer: The betaFEC design work started a few sprints before the US Web Design Standards gathered a project team that began researching and strategy setting. We needed to determine a look and feel for the new FEC site too far ahead of when the web design standards had an inkling of what their recommended visual styles would be. We were able to contribute to the research when USWDS was defining their visual styles, but we needed to keep our product moving. 🐔 + :egg:  👎  We do continue to use the USWDS UI component structure, but in betaFEC's visual styles. 

It would certainly be possible for the FEC to convert to the USWDS later on if that was prioritized. (The typography systems aren't _too_ far apart, but the color system on betaFEC is pretty specific and intentional, I'm not sure the USWDS palette would meed the FEC's needs and goals. Oops, tangent started!) 

**A follow-up question for you:**
Understanding where folks look for this info will help us put it in the right place(s). You mentioned that you might put the answer to this in the Wiki or the README.md file. Were there any other places you looked before filing this issue?

**Comment by asarazor** [comment]
Thanks for the comprehensive answer, Jennifer. I had no idea that the FEC redesign started that far back.

As to your follow up: I scanned the README and Wiki on this repo and the README on the [FEC Discussion/Feedback](https://github.com/18F/fec) repo. Scanned the [story map](https://18f.storiesonboard.com/m/fec), then just googled all the relevant domains (18F.gsa.gov, standards.usa.gov) with the keywords, as I had no idea where this information may reside. That revealed a reference in [a design discussion here](https://github.com/18F/fec-style/issues/498) plus some CSS comments. That's why I decided to create the issue here.

In hindsight I didn't check the [FEC Discussion/Feedback wiki](https://github.com/18F/FEC/wiki), which I see now is quite rich in information.

If you agree that this is worthwhile to document, then that is probably the canonical place for it,  perhaps linked to from the READMEs.

In general some background info on the project would have been helpful to me (in order to inform similar efforts at my own govt. agency). The READMEs currently just give us the value proposition that you probably crafted later down the line. So, if you like telling stories, you could collate this very specific historical constraint alongside some other narrative and links to [previous 18F bog posts](https://18f.gsa.gov/2014/08/21/creating-an-open-fec/), then place it in *Background* page or similar.

**Comment by jenniferthibault** [comment]
Issue moved to [18F/fec-pattern-library #43](https://github.com/18F/fec-pattern-library/issues/43) via [**ZenHub**](https://www.zenhub.com/)
