### ISSUE TITLE
Finalize site navigation menus

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#655]
We kind of left the [last site nav](https://github.com/18F/fec-cms/issues/827) thread hanging, so I wanted to make a fresh issue so we can resolve all remaining issues, both in the content and development. 

In addition to finalizing language (now that we have a new name for the compliance section) we should also decide if we're keeping the search bar in the campaign finance data one as well. 

**Completion criteria**
- [x] Finalize structure
- [x] Finalize language
- [x] Implement desktop views with correct links
- [x] Implement mobile views with correct links

**Comment by jenniferthibault** [comment]
I just added one completion criteria above to _Finalize structure_ , which this update tackles.

@noahmanger and I paired to work through finding a better way to show consistent structures and elements across the three categories. Here's what we're thinking:

- Use the content from the hero panel to give an intro to the section. The "...home" and "Get started" would both link to that section's landing page.
- User distinct type styles to represent 1) a section* (most often a landing page), and 2) a sub-section of that page
  - _*The reason it's "most often" and not "always" a landing page is the `Elections` section in data, which does not have it's own landing, but that may evolve as the election tools are fleshed out. It certainly feels enough like its own area within data to have a headline for now, even though that would be the only non-linking headline. It just means our rules aren't perfect for now._
- We removed the sub-sections for the "Help for candidates and committees" section (H4CC, 🙄 already annoyed with myself, but i really hate writing it out, sorry!), since there isn't unique value to having it here: it feels like the H4CC page is short enough that it won't be missed, AND there's a side nav on that page that captures it as well. If those entities had their own landing pages (or section landing pages, like Adv data), it would make more sense to put those links in the nav. 

![screen shot 2017-03-29 at 4 25 30 pm](https://cloud.githubusercontent.com/assets/11636908/24475062/c0281a40-149c-11e7-9819-eb52e28a86ac.png)

![screen shot 2017-03-29 at 4 29 52 pm](https://cloud.githubusercontent.com/assets/11636908/24475157/fb78abbe-149c-11e7-87c5-747760ccc144.png)

![screen shot 2017-03-29 at 4 25 57 pm](https://cloud.githubusercontent.com/assets/11636908/24475063/c0285d48-149c-11e7-9d50-ec67be69fbd8.png)

@emileighoutlaw and @nickykrause , what do you think?

**Comment by emileighoutlaw** [comment]
I think these designs look really strong. I am especially excited to see these introductions brought in. It's a really nice clue to help differentiate these sections.

✏️  Can we change `Deadlines` in the H4CC dropdown to say `Dates and deadlines`, which is an important distinction to the FEC folks?

💡  The header in the dropdown for H4CC feels a little more crowded than the other two sections, because the name is so long. It's harder to shorten now that it's `Help` and not `Services`. But what do you think of `Candidates and committees home` as an option? 

❔ A thought about removing the committee types from H4CC drop-down: I think you're totally right that if people get to the landing page, the options are very clear. But I worry that this design highlights only the supplemental pages that we created to help a specific set of users with advanced content needs, rather than the meat and potatoes of what this section is. I find myself asking _what is the purpose/goal of this navigation?_, which seems like a stupid/foundational question. But I'm not 100% sure of the answer. Would love to know if @nickykrause has thoughts about any of this, too.

**Comment by noahmanger** [comment]
Responding to your last point: fair question, but I think there's three tangible purposes:
- I think the menu is important for consistency, so that all three top-level sections behave similarly
- Through the intro blurb and the supplemental pages, it also reinforces what the purpose of this section is
- I think those supplemental pages _are_ important to link directly to from the menu

As for the title, I'm inclined to think that we should use the full verbose names for everything, rather than truncating. I think truncating can just lead to confusion.

**Comment by emileighoutlaw** [comment]
Cool— so you think we revise the other drop-downs to read `Campaign finance data home` and `Legal resources home` ?

I'm game for trying out omitting the names of the groups in the drop-downs if we do some specific testing around this as soon as possible? We know that _without_ a drop-down menu, folks had no problem navigating to the landing page and then into the group types. But I'd like to know if folks navigate as effectively with this new drop-down. Basically, I have some mega-anxiety about this that I think only user testing will alleviate.

**Comment by jenniferthibault** [comment]
💯 to testing on this!

I'm 51/49 in favor of truncating vs using the full titles+home, but realized that my last mockups were inconsistent in how they were truncated.

So it's :
- Data home
- Candidates and committees home
- Legal home

OR
- Campaign finance data home
- Help for candidates and committees home
- Legal resources home

The +1 point lading to my preference to truncate is that it's faster for scanning and more direct to find the word "home", which signals a place to go and not just repetitive labeling

**Comment by emileighoutlaw** [comment]
I agree with Jen on the "home" being really important for scanning and prefer the truncated as well :)

**Comment by nickykrause** [comment]
Sorry for being so late to the game here! You all have great brains...the more I read, the more I thought "Yep! good point - but wait...? Oh, yep, someone asked that, and yep, a thoughtful answer..."

Anyway, all of that is just to say that I found myself agreeing with multiple angles of each question, and I agree that we should do testing. 

To get some thoughts clear for testing -- these are the questions & hypotheses that I understand us to have for testing the menu:

---

- Should we truncate?
> Theory: Truncating the titles will make it easier for users to scan the link options and to find the word "home"

💡 Hypothesis: Users who use the drop-down menu will easily recognize the "home" links and will not be distracted or confused by the truncated names.

---

- Does the drop-down over-emphasize "supplemental" content? 
> **Theory**: Because the supplemental content in the drop-down surfaces info that people might not otherwise find, it is helpful to have it there. 

💡 Hypothesis: People who are looking for supplemental content will have an easier time finding it via the drop-down menu than people who use another method.

---

- Should we link to the different committee types in H4CC in the drop-down? 
> **Theory**  Because people can easily navigate to their unique sections using the landing page, it is not necessary to include those links in the drop-down menu. Although these links would be the "meat and potatoes" of the section, users who are seeking them will be assisted by the section description in the menu.

💡 Hypothesis: People who are looking for specific committee type information and who use the drop-down will navigate to the landing page and successfully will find the appropriate committee-type content.

**Comment by emileighoutlaw** [comment]
I cannot convey how much I love Nicky's ability to bring research rigor to my poorly collected thoughts

**Comment by nickykrause** [comment]
Aw thanks, @emileighoutlaw  😄   Your thoughts were not poorly collected at all! I was just trying to get my mind around how we would test this to actually answer the questions we have.

So, it sounds like we're good with proceeding to implement the mockups Jen had above, except for the two small changes:

✏️  Keep the truncated links consistent (so, making them say Data home, Candidates and committees home, Legal home)

and

✏️ Change Deadlines in the H4CC dropdown to say Dates and deadlines, which is an important distinction to the FEC folks

Is that right?

**Comment by emileighoutlaw** [comment]
That sounds right to me :)

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-style/pull/642

This will be going up soon!
