### ISSUE TITLE
Add new social media images

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#670]
So that links shared on social media entice users to click through, create new social media share images for the site.

---

**Completion criteria:**
- [x] New images added to web app and CMS
- [x] Each of the three sections should show their own unique share image
- [x] All other pages should show the generic image

cc @jenniferthibault

**Comment by jenniferthibault** [comment]
⚠️ Long post warning ⚠️ 
Feel free to skip straight to the **"❓ Open question"** headline if you prefer to skip the background and rationale.
________________________

## Current images:
Universal thumbnails in two formats that introduced the beta site: the focus is on clean design and beta identity:
![screen shot 2017-04-14 at 3 57 04 pm](https://cloud.githubusercontent.com/assets/11636908/25054419/076df524-212b-11e7-9152-1d0863c34d62.png)

## A few objectives for the new design
- Let people know change has happened
- Get more specific about what's being shared
- Communicate the site is more comprehensive and has moved out of beta

## Light research
- 🔒 [Mural with quick audit](https://app.mural.ly/t/gsa6/m/gsa6/1492112985279/view/2979126361) of what some other agencies are doing, most clips are from the perspective of the home page

**Trends**
- Specific to whatever initiatives are being highlighted on the home page, seem rotational and pulled from feature images instead of built custom.
- Agency seal/logo/tagline
- Image evocative of agency's subject matter (sometimes combined & overlaid with seal)
- Government buildings (more effective for easily recognizable ones, like the Senate building)

**How current users share fec.gov & beta.fec.gov links**
- Many users share FEC links pointing to "the official source" - and are interested in pointing out the specific content on the page, especially related to data: users often take their own screenshots, edit them to highlight or annotate what they want to focus on, and upload them to share.
While we can't offer this highly-specific functionality (for now?) what we can do is offer more specificity into the part of the site they're looking at through imagery than we have been until now.

## New concepts
- Have unique images for our current three nav areas (data, help, legal) and a more generalized image for the landing page & other supplementary content
- Continue to keep it clean and simple
- Keep the full agency name in the image to reinforce that what people are sharing is "the official" source

### ❓ Open question — The seal feels too busy for the individual section images, but does the image feel sufficiently "official" without it?

I've laid out the same series of images with and without the seal present in each, what our team should decide is which combination we'd like to use.

#### General, with and without seal
![screen shot 2017-04-14 at 4 03 38 pm](https://cloud.githubusercontent.com/assets/11636908/25054585/fc84e68a-212b-11e7-8ac4-269305f8d0e1.png)

#### Specific, with and without seal
![screen shot 2017-04-14 at 4 06 21 pm](https://cloud.githubusercontent.com/assets/11636908/25054646/576746a6-212c-11e7-9b11-d4a4f9ad0e89.png)

The smaller square images follow the same pattern, so I'm omitting them for the moment while we focus on some other decisions.

### Here are those options in context:

#### All with seal (left), all without seal (right)
![screen shot 2017-04-14 at 4 19 56 pm](https://cloud.githubusercontent.com/assets/11636908/25054997/4d4abe76-212e-11e7-9ba6-6bcd84b69562.png)



#### Seal for generic, not for specific
![screen shot 2017-04-14 at 4 20 12 pm](https://cloud.githubusercontent.com/assets/11636908/25054998/513343c8-212e-11e7-9b67-b51d7be70286.png)

___________________________________
## Decision time
Originally I was Team Never Seal to keep things cleaner, but once I popped the image into the feeds, I think we at least need the seal on the generic pages. I'm not yet sure if we need them on the specific pages, but I'm leaning toward starting without to balance out visual simplicity. That would give the last image above for our starting point.

Thoughts ?

@onezerojeremy @nickykrause @emileighoutlaw @noahmanger

**Comment by jenniferthibault** [comment]
Hi @ChristianHilland — I think it would be great if you and Judy could take a look at this issue and chime in with perspective from the press office. In the comment above this, I've written out some background & research for what we have now and what we hope to accomplish. Questions welcome!

**Comment by ChristianHilland** [comment]
I would say that I am on Team Never Seal as well, as these images bring a "simple and clean" design.  However, I do think the seal serves a purpose in that the members of public recognize it as belonging to the FEC. I believe using the seal on the generic images and not the specific ones would strike the right balance and would be sufficient.  @jenniferthibault, Please let me know if you any additional questions.

**Comment by jenniferthibault** [comment]
Thanks Christian!

**Comment by jenniferthibault** [comment]
Here are the images at various sizes zipped & ready. I wasn't sure how to add them to the code or label them, since we're using different ones in each section, which is different than our current model, so these files may need to be re-organized or renamed at the least.

[postFlip_social-images.zip](https://github.com/18F/fec-style/files/935153/postFlip_social-images.zip)

**Comment by noahmanger** [comment]
@jenniferthibault can you add a size for Twitter cards? The rectangle you have is right for Facebook, but we need one that's 2:1 ratio (see: https://dev.twitter.com/cards/types/summary-large-image)

**Comment by jenniferthibault** [comment]
Since the Facebook image was 1200 x 630, which is just shy of 1.91:1, I wonder if we can try using one image for both. Here are those images at 1200x600, or 2:1
[2-1.zip](https://github.com/18F/fec-style/files/977178/2-1.zip)

**Comment by noahmanger** [comment]
Resolved by https://github.com/18F/fec-cms/pull/1053
