### ISSUE TITLE
Create inventory of components for the pattern library

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-style#696]
So that we can begin to build out the pattern library, first create an inventory of all components that we're currently using and organize into the IA from #292 .

**Comment by jenniferthibault** [comment]
I wasn't able to complete this before leaving for OOO time, but I've started a more complete and granular inventory in [this Mural,](https://app.mural.ly/t/gsa6/m/gsa6/1482528529043/view/1501547309) 🎨 🗒  and will continue to flesh it out.

**Comment by jenniferthibault** [comment]
We're doing this a bit more fluently than this issue conveys: @xtine and I have been re-organizing and updates the components that are currently in the pattern library. Later we'll add in patterns that aren't there yet. It was feeling like we were blocking ourselves from making real progress by not starting on things until there was a complete inventory of existing components. 

I wouldn't say this issue is "Done", but if we leave it as is, it will be in progress for a while. Maybe we close in favor of #725 ?
